/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsEnum,
  IsNumber,
  Min,
  Max,
} from "class-validator";

import { CoachWhereUniqueInput } from "../../coach/base/CoachWhereUniqueInput";
import { Type } from "class-transformer";
import { EnumVideoEncodingStatus } from "./EnumVideoEncodingStatus";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { SubscriptionUpdateManyWithoutVideosInput } from "./SubscriptionUpdateManyWithoutVideosInput";

@InputType()
class VideoUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  category?: string | null;

  @ApiProperty({
    required: false,
    type: () => CoachWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CoachWhereUniqueInput)
  @IsOptional()
  @Field(() => CoachWhereUniqueInput, {
    nullable: true,
  })
  coach?: CoachWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumVideoEncodingStatus,
  })
  @IsEnum(EnumVideoEncodingStatus)
  @IsOptional()
  @Field(() => EnumVideoEncodingStatus, {
    nullable: true,
  })
  encodingStatus?: "Option1" | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  outputUrls?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    type: () => SubscriptionUpdateManyWithoutVideosInput,
  })
  @ValidateNested()
  @Type(() => SubscriptionUpdateManyWithoutVideosInput)
  @IsOptional()
  @Field(() => SubscriptionUpdateManyWithoutVideosInput, {
    nullable: true,
  })
  subscriptions?: SubscriptionUpdateManyWithoutVideosInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  thumbnailUrls?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  url?: string | null;
}

export { VideoUpdateInput as VideoUpdateInput };
