/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { GraphQLUpload } from "graphql-upload";
import { FileUpload } from "src/storage/base/storage.types";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Coach } from "./Coach";
import { CoachCountArgs } from "./CoachCountArgs";
import { CoachFindManyArgs } from "./CoachFindManyArgs";
import { CoachFindUniqueArgs } from "./CoachFindUniqueArgs";
import { CreateCoachArgs } from "./CreateCoachArgs";
import { UpdateCoachArgs } from "./UpdateCoachArgs";
import { DeleteCoachArgs } from "./DeleteCoachArgs";
import { CertificationFindManyArgs } from "../../certification/base/CertificationFindManyArgs";
import { Certification } from "../../certification/base/Certification";
import { VideoFindManyArgs } from "../../video/base/VideoFindManyArgs";
import { Video } from "../../video/base/Video";
import { CoachService } from "../coach.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Coach)
export class CoachResolverBase {
  constructor(
    protected readonly service: CoachService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Coach",
    action: "read",
    possession: "any",
  })
  async _coachesMeta(
    @graphql.Args() args: CoachCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Coach])
  @nestAccessControl.UseRoles({
    resource: "Coach",
    action: "read",
    possession: "any",
  })
  async coaches(@graphql.Args() args: CoachFindManyArgs): Promise<Coach[]> {
    return this.service.coaches(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Coach, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Coach",
    action: "read",
    possession: "own",
  })
  async coach(
    @graphql.Args() args: CoachFindUniqueArgs
  ): Promise<Coach | null> {
    const result = await this.service.coach(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Coach)
  @nestAccessControl.UseRoles({
    resource: "Coach",
    action: "create",
    possession: "any",
  })
  async createCoach(@graphql.Args() args: CreateCoachArgs): Promise<Coach> {
    return await this.service.createCoach({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Coach)
  @nestAccessControl.UseRoles({
    resource: "Coach",
    action: "update",
    possession: "any",
  })
  async updateCoach(
    @graphql.Args() args: UpdateCoachArgs
  ): Promise<Coach | null> {
    try {
      return await this.service.updateCoach({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Coach)
  @nestAccessControl.UseRoles({
    resource: "Coach",
    action: "delete",
    possession: "any",
  })
  async deleteCoach(
    @graphql.Args() args: DeleteCoachArgs
  ): Promise<Coach | null> {
    try {
      return await this.service.deleteCoach(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Coach)
  async uploadProfilePicture(
    @graphql.Args({
      name: "file",
      type: () => GraphQLUpload,
    })
    file: FileUpload,
    @graphql.Args()
    args: CoachFindUniqueArgs
  ): Promise<Coach> {
    return await this.service.uploadProfilePicture(args, file);
  }

  @graphql.Mutation(() => Coach)
  async deleteProfilePicture(
    @graphql.Args()
    args: CoachFindUniqueArgs
  ): Promise<Coach> {
    return await this.service.deleteProfilePicture(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Certification], { name: "certifications" })
  @nestAccessControl.UseRoles({
    resource: "Certification",
    action: "read",
    possession: "any",
  })
  async findCertifications(
    @graphql.Parent() parent: Coach,
    @graphql.Args() args: CertificationFindManyArgs
  ): Promise<Certification[]> {
    const results = await this.service.findCertifications(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Video], { name: "videos" })
  @nestAccessControl.UseRoles({
    resource: "Video",
    action: "read",
    possession: "any",
  })
  async findVideos(
    @graphql.Parent() parent: Coach,
    @graphql.Args() args: VideoFindManyArgs
  ): Promise<Video[]> {
    const results = await this.service.findVideos(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
